# Generated by Django 4.1.3 on 2023-04-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="Description",),
        migrations.RemoveField(model_name="submission", name="Github",),
        migrations.RemoveField(model_name="submission", name="Hackathon_enddate",),
        migrations.RemoveField(model_name="submission", name="Hackathon_name",),
        migrations.RemoveField(model_name="submission", name="Hackathon_startdate",),
        migrations.RemoveField(model_name="submission", name="Other",),
        migrations.RemoveField(model_name="submission", name="Summary",),
        migrations.RemoveField(model_name="submission", name="Title",),
        migrations.RemoveField(model_name="submission", name="image",),
        migrations.RemoveField(model_name="submission", name="last_edited",),
        migrations.RemoveField(model_name="submission", name="pub_date",),
    ]
