# Generated by Django 4.1.3 on 2023-04-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("Title", models.TextField(verbose_name="title")),
                ("Summary", models.TextField(blank=True, verbose_name="summary")),
                ("Description", models.TextField(blank=True, verbose_name="summary")),
                ("Hackathon_name", models.TextField(verbose_name="hackathonname")),
                (
                    "Hackathon_startdate",
                    models.DateField(verbose_name="hackathonstartdate"),
                ),
                (
                    "Hackathon_enddate",
                    models.DateField(verbose_name="hackathonenddate"),
                ),
                ("Github", models.TextField(verbose_name="github")),
                ("Other", models.TextField(blank=True, verbose_name="others")),
                ("image", models.ImageField(default=None, upload_to="")),
            ],
        ),
    ]
